# Generated by Django 3.0.6 on 2020-07-28 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('auteur', models.CharField(max_length=255)),
                ('langue', models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais'), ('SP', 'Espagnol'), ('PE', 'Portugais'), ('AL', 'Allemand'), ('CH', 'Chinois'), ('AR', 'Arabe'), ('RU', 'Russe'), ('IT', 'Italien'), ('AU', 'Autre')], default='FR', max_length=100)),
                ('source', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_pub', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Constitution', 'Constitution'), ('Loi', 'Loi'), ('Décret', 'Décret'), ('Programme/plan', 'Programme/plan')], default='Constitution', max_length=15, verbose_name='Type de document')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('AF', 'Afrique'), ('AC', 'Amerique latine et Caraibes'), ('AP', 'Asie et Pacifique'), ('EA', 'Etats arabes'), ('EU', 'Europe'), ('AM', 'Amerique du Nord')], default='AF', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=255)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Region')),
                ('documents', models.ManyToManyField(to='api.Document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nature'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
