# Generated by Django 3.0.6 on 2020-07-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_pub',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='documents/'),
        ),
    ]
